project:
  type: website

website:
  title: "MOTION-BIDS"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Materials
      - href: authors.qmd
        text: Authors
      
body-footer: |
  ![BIDS logo](/pics/BIDS_Logo.png)

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
