project:
  type: website

website:
  title: "MOTION-BIDS resources"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
body-footer: |
  ![BIDS logo](BIDS_logo.png)

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
