---
title: "Resources"
---

This page provides resources for the MOTION-BIDS project.

## MOTION-BIDS specification
The MOTION-BIDS specification is available on the [MOTION-BIDS documentation website](https://bids-specification.readthedocs.io/en/stable/modality-specific-files/motion.html).

## Publication 
The MOTION-BIDS paper is available [online](https://www.nature.com/articles/s41597-024-03559-8).

## IGOR BIDS consultation hour
Thanks to IGOR, we offer a consultation hour for BIDS related questions. 
The consultation hour is open to everyone who is interested in BIDS or has questions about how to convert data to BIDS.
[Website](https://juliuswelzel.github.io/igor_bids_consultation/)

## Workshops and presentations 
Here are some talks or posters about MOTION-BIDS from the past :

- GAMMA Workshop, Kiel 2024 - Workshop by Julius Welzel
  [Slides](slides/2410_gamma_welzel.pdf)
- BIDS workshop CBBM Lübeck, 2024 - Talk/Workshop by Julius Welzel
  [Slides](slides/2410_bidsIntro_luebeck_welzel.pdf.pdf)
- Mobile Brain Imaging Conference (MOBI), Piran, 2024 - Workshop by Sein Jeung & Julius Welzel
  [Slides](slides/2406_ngmt_mobi.pdf)
- Psychologie & Gehirn ([IGOR Prize](https://www.dgps.de/fachgruppen/fgbi/aktivitaeten-der-fachgruppe/igor/)), Hamburg 2024 - Poster by Julius Welzel 
  [Poster](slides/08_welzel.pdf)
- Open Science Series, Oldenburg 2024 - Workshop by Julius Welzel
  [Slides](slides/2405_bidsIntro_oldenburg_welzel.pdf)
- Methods In Mobile EEG, Belgrade 2023 - Workshop by Julius Welzel 
  [Slides](https://juliuswelzel.github.io/bids_belgrade_2023/#/title-slide)

Related talks about BIDS : 

- Neuroergonomics Conference, Bordeaux 2024 - Multimodal BIDS Workshop by Sein Jeung & Lukas Gehrke 
- Open Science Series, DGPA, 2024 - Workshop by Sein Jeung & Julius Welzel
  [Slides](slides/2410_dgpa_welzel_jeung.pdf)

## Tutorials & repositories
You can browse the tutorials to get started with MOTION-BIDS or BIDS in general:

- BIDS specification, a greate place to start - [Link](https://bids-specification.readthedocs.io/)
- Motion data to BIDS in Fieldtrip - [Link](https://www.fieldtriptoolbox.org/example/bids_motion/)
- Scripts for converting XDF data to BIDS  - [Link](https://github.com/sjeung/multimodal_XDF-to-BID)
- Github repo with workshop material for Python - [Link](https://github.com/JuliusWelzel/bids_workshop)

## Example data sets
- Data sets on BIDS-examples demonstrate file names and folder structure but do not include the actual data. Data set 2. is found in full version on OpenNeuro, see link below.
  - 1. Data set ["dual task"](https://github.com/bids-standard/bids-examples/tree/master/motion_dualtask) shows data from optical motion capture system used with EEG. Provided by Janna Protzak & Klaus Gramann. 
  - 2. Date set ["spot rotation"](https://github.com/bids-standard/bids-examples/tree/master/motion_spotrotation) contains data from another EEG + motion capture experiment with optical and VR-based motion tracking. On OpenNeuro the [full data set](https://openneuro.org/datasets/ds004460/versions/1.1.0) is found including position, orientation values as well as EEG data. Provided by Klaus Gramann, published as Gramann et al., (2021) "Human cortical dynamics during full-body heading changes". 
  - 3. Data set ["system validation"](https://github.com/bids-standard/bids-examples/tree/master/motion_systemvalidation) contains motion data collected using IMUs and an optical system simultaneously. Provided by Elke Warmerdam, published as Warmerdam et al., (2021) "Proposed Mobility Assessments with Simultaneous Full-Body Inertial Measurement Units and Optical Motion Capture in Healthy Adults and Neurological Patients for Future Validation Studies: Study Protocol".
